[package]
name = "lua-int"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
utf8-decode = "1.0.1"

[lib]
name = "lua_int"
crate-type = ["cdylib", "lib"]
